@startuml
skinparam packageStyle rectangle

left to right direction
    actor as "Operator"

rectangle {
    usecase "Upload Requirements Specification File,\n with the answers from the Candidate" as UC1

    actor --> UC1

}
@enduml