@startuml
skinparam packageStyle rectangle

left to right direction
    actor as "Costumer Manager"

rectangle {
    usecase "Notify Customer and Candidates about the results" as UC1

    actor --> UC1

}
@enduml