@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 1019

autonumber

actor "Customer Manager" as User
participant ":System" as System

activate User

    User -> System: Asks list Candidates \nby Interview Points
        activate System

    System--> User : Lists Job Openings
        deactivate System

    User -> System: Selects a Job Opening
        activate System

    System--> User : Lists Candidates
        deactivate System

@enduml