@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 1000

autonumber

actor "Admin" as User
participant ":System" as System

activate User

    User -> System: asks to register a new backoffice user
        activate System

    System--> User : requests data
        deactivate System

    User -> System: types requested data (first name, last name,\n email, password)
        activate System

    System-> User : displays roles list and asks to select
        deactivate System

        User -> System: selects role
                activate System

            System--> User : shows operation success
                deactivate System

@enduml