@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 1017

autonumber

actor "Customer Manager" as User
participant ":System" as System

activate User

    User -> System: asks to upload Interview file
        activate System

    System--> User : Lists Job Openings
        deactivate System

    User -> System: Selects a Job Opening
        activate System

    System--> User : Shows Operation Success
            deactivate System

@enduml