@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 2000a

autonumber

actor "Customer Manager" as User
participant ":System" as System

activate User

    User -> System: asks to list a job opening
        activate System

    System--> User : shows job openings
        deactivate System

@enduml