@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 1011

autonumber

actor "Customer Manager" as User
participant ":System" as System

activate User

    User -> System: asks to select a interview\n model for a job opening
        activate System

    System--> User : lists job openings
        deactivate System

    User -> System: selects a job opening
        activate System

        System--> User : lists interview model\n plugins in the system
            deactivate System

        User -> System: selects a interview model
            activate System

            System--> User : shows operation success
                deactivate System

@enduml