@startuml
skinparam monochrome true
skinparam packageStyle rectangle
skinparam shadowing false

title System Sequence Diagram (SSD) - US 2003

autonumber

actor "Customer Manager" as User
participant ":System" as System

activate User

    User -> System: asks to generate interview template
        activate System

    System--> User : displays job openings
        deactivate System

    User -> System: selects job opening
        activate System

    System--> User : shows operation success
        deactivate System

@enduml